name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
# allow manual trigger

jobs:
  build:
    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build net8
      run: dotnet build ModdableWebServer/ModdableWebServer.csproj -v:n -f net8.0 -o Out/net8

    - name: Build net9
      run: dotnet build ModdableWebServer/ModdableWebServer.csproj -v:n -f net9.0 -o Out/net9

    - name: Test
      run: dotnet test -v:n

    - name : Upload
      uses: actions/upload-artifact@v4.3.5
      with:
        name: ModdableWebServer
        path: Out/*